apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  container:
    - name: resource-demo
      image: polinux/stress
      command: ["stress"]
      resources:
        requests:
          memory: "200Mi"
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1